# Makefile generated by OpenModelica

# Simulations use -O3 by default
CC=gcc
CXX=g++
LINK=g++ -shared -Xlinker --export-all-symbols -fPIC
EXEEXT=.exe
DLLEXT=.dll
CFLAGS_BASED_ON_INIT_FILE=
DEBUG_FLAGS=
CFLAGS=$(CFLAGS_BASED_ON_INIT_FILE) $(DEBUG_FLAGS) ${SIM_OR_DYNLOAD_OPT_LEVEL} -falign-functions -msse2 -mfpmath=sse ${MODELICAUSERCFLAGS}    
CPPFLAGS= -I"C:/OpenModelica1.12.0-64bit//include/omc/c" -I. -DOPENMODELICA_XML_FROM_FILE_AT_RUNTIME -DOMC_MODEL_PREFIX=Graph -DOMC_NUM_MIXED_SYSTEMS=0 -DOMC_NUM_LINEAR_SYSTEMS=0 -DOMC_NUM_NONLINEAR_SYSTEMS=80 -DOMC_NDELAY_EXPRESSIONS=0 -DOMC_NVAR_STRING=0
LDFLAGS=-L"C:/Users/thant/OneDrive/Desktop/IITB Capstone/Main Project/Chemical-Simulator-GUI-master/Simulator" -L"C:/OpenModelica1.12.0-64bit//lib//omc" -L"C:/OpenModelica1.12.0-64bit//lib" -Wl,--stack,16777216,-rpath,"C:/OpenModelica1.12.0-64bit//lib//omc" -Wl,-rpath,"C:/OpenModelica1.12.0-64bit//lib"   -lregex -lexpat -lomcgc -lpthread -fopenmp -loleaut32 -limagehlp -lz -lhdf5  -lSimulationRuntimeC -lomcgc -lexpat -lregex -static-libgcc -luuid -loleaut32 -lole32 -limagehlp -lws2_32 -llis -lumfpack -lklu -lcolamd -lbtf -lamd -lsundials_idas -lsundials_kinsol -lsundials_nvecserial -lipopt -lcoinmumps -lpthread -lm -lgfortranbegin -lgfortran -lmingw32 -lgcc_eh -lmoldname -lmingwex -lmsvcrt -luser32 -lkernel32 -ladvapi32 -lshell32 -lopenblas -lcminpack -lwsock32 -lstdc++ 
MAINFILE=Graph.c
MAINOBJ=Graph.o
CFILES=Graph_functions.c Graph_records.c \
Graph_01exo.c Graph_02nls.c Graph_03lsy.c Graph_04set.c Graph_05evt.c Graph_06inz.c Graph_07dly.c \
Graph_08bnd.c Graph_09alg.c Graph_10asr.c Graph_11mix.c Graph_12jac.c Graph_13opt.c Graph_14lnz.c \
Graph_15syn.c Graph_16dae.c Graph_17inl.c 

OFILES=$(CFILES:.c=.o)
GENERATEDFILES=$(MAINFILE) Graph.makefile Graph_literals.h Graph_functions.h $(CFILES)

.PHONY: omc_main_target clean bundle

# This is to make sure that Graph_*.c are always compiled.
.PHONY: $(CFILES)

omc_main_target: $(MAINOBJ) Graph_functions.h Graph_literals.h $(OFILES)
	$(CC) -I. -o Graph$(EXEEXT) $(MAINOBJ) $(OFILES) $(CPPFLAGS) -L"C:/Users/thant/OneDrive/Desktop/IITB Capstone/Main Project/Chemical-Simulator-GUI-master/Simulator"   $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)
clean:
	@rm -f Graph_records.o $(MAINOBJ)

bundle:
	@tar -cvf Graph_Files.tar $(GENERATEDFILES)